name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: pytest --html=pytest-report.html

    - name: Run Flake8
      run: flake8 . --format=html --htmldir=flake8-report

    - name: Upload Pytest Report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: pytest-report.html

    - name: Upload Flake8 Report
      uses: actions/upload-artifact@v3
      with:
        name: flake8-report
        path: flake8-report
